title: blowmore
header_title: blowmore.org
subtitle: software that blows more
url: "https://blowmore.org"
baseurl: ""

menu:
  - id: home
    label: home
    url: /
  - id: gsus
    label: gsus
    url: /gsus/about.html

external_menu:
  - label: github
    url: https://github.com/blowmore

exclude:
  - README.md
