title: blowmore
header_title: blowmore.org
subtitle: software that blows more
url: "https://blowmore.org"
baseurl: ""

menu:
  - id: home
    label: home
    url: /
  - id: aslan
    label: aslan
    url: /gsus/aslan.html
  - id: gsus
    label: gsus
    url: /gsus/about.html

sidebars:
  home:
    - id: about
      label: about
      url: /index.html
    - id: people
      label: people
      url: /people.html
  aslan:
    - id: about
      label: about
      url: /aslan/about.html
  gsus:
    - id: about
      label: about
      url: /gsus/about.html

external_menu:
  - label: github
    url: https://github.com/blowmore

exclude:
  - README.md
